# Generated by Django 6.1 on 2026-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_backenduser_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backenduser',
            name='isadmin',
            field=models.BooleanField(default=False),
        ),
    ]
